### ISSUE TITLE
Minor Enhancmet: indeces.py can be defined as an IntEnum class

### ISSUE THREAD

**Issue by f-shaker** [DUNE/larnd-sim#16]
Minor Enhancmet: indeces.py can be defined as an IntEnum class

from enum import IntEnum
class Indices(IntEnum):
    eventID = 0
    x_start = 1
Then we can also use the at-unique decorator if needed to prevent 2 members of having the same value

@soleti 
Is there a reason for the order of these indices? For instance why z_end if before z_start but after x_start?
eventID = 0
x_start = 1
dE = 2
z_end = 3

**Comment by soleti** [comment]
This is related to issue #21 which should solve the same problem.
