### ISSUE TITLE
Update the coefficients of the Box quenching model

### ISSUE THREAD

**Issue by f-shaker** [DUNE/larnd-sim#19]
The coefficients of the box model in the JINST paper:
"A study of electron recombination using highly ionizing particles in the ArgoNeuT Liquid Argon TPC" 
R. Acciarri a , C.
https://arxiv.org/pdf/1306.1712.pdf
are defined as (for all tracks angles 20 to 90 degrees) alpha = 0.93 and beta = 0.319 
c.f table 2 of the above paper. 
In the [consts.py](https://github.com/DUNE/larnd-sim/blob/master/larndsim/consts.py#L20-23) module these values are defined as 
alpha = 0.847 and beta = 0.2061
These values largely affect the quenching curve as seen in the attached plots
![box_briks](https://user-images.githubusercontent.com/41970450/105643027-6d141680-5e5b-11eb-8929-e01dd123e6cd.png)
![quench_models_a0 93_b0 319](https://user-images.githubusercontent.com/41970450/105643028-6d141680-5e5b-11eb-8ff9-df8179c19309.jpg)
![quench_models_a0 847_b0 2601](https://user-images.githubusercontent.com/41970450/105643029-6d141680-5e5b-11eb-93de-6d749ad845a5.jpg)

**Comment by soleti** [comment]
Thanks Fady for catching this. I am sure I found those numbers somewhere, but I can't remember where, so better to use an established reference. Please feel free to open a pull request with the new values.

**Comment by f-shaker** [comment]
Thanks Roberto. I will add a couple of pytest cases for the quenching to detect any change in the used model parameters, and will issue a pull request that include the modifications in the const.py and the testQuenching.py files.
