### ISSUE TITLE
Conflict between examples/cosmic_qc_tpc.p track segments features order (and numbers) and the indeces.py ordering

### ISSUE THREAD

**Issue by f-shaker** [DUNE/larnd-sim#22]
There is a conflict between the order of the track segments features and that in the [indeces.py](https://github.com/DUNE/larnd-sim/blob/master/larndsim/indeces.py) module. This difference will make the "Quenching and drifting.ipynb" notebook fail due to errors like:
1. division by zero (due to wrong i.de order)
2. index out of array size (for the i.z ) 

This problem will be fixed with the implementation of issue #21 

An example of the picle file order is provided here:
---------------------------------------------------------------------
index: 0: name: eventID : e.g. element[0] value: 4 
index: 1: name: dEdx : e.g. element[0] value: 1.8036283891216403 
index: 2: name: x_start : e.g. element[0] value: -8.12253151832159 
index: 3: name: dE : e.g. element[0] value: 12.567597389221191 
index: 4: name: t_start : e.g. element[0] value: 0 
index: 5: name: z_end : e.g. element[0] value: 0.6317725013094009 
index: 6: name: trackID : e.g. element[0] value: 0 
index: 7: name: x_end : e.g. element[0] value: -7.60157384726227 
index: 8: name: y_end : e.g. element[0] value: 4.3000314360330645 
index: 9: name: n_electrons : e.g. element[0] value: 0 
index: 10: name: t : e.g. element[0] value: 0 
index: 11: name: dx : e.g. element[0] value: 6.967952747373621 
index: 12: name: pdgId : e.g. element[0] value: 13 
index: 13: name: y : e.g. element[0] value: 7.566239754138391 
index: 14: name: x : e.g. element[0] value: -7.862052682791931 
index: 15: name: long_diff : e.g. element[0] value: 0 
index: 16: name: z : e.g. element[0] value: 1.8158862506547002 
index: 17: name: z_start : e.g. element[0] value: 3.0 
index: 18: name: y_start : e.g. element[0] value: 10.832448072243718 
index: 19: name: tran_diff : e.g. element[0] value: 0 
index: 20: name: t_end : e.g. element[0] value: 0

**Comment by soleti** [comment]
Fixed by cb61e96
