### ISSUE TITLE
h5 file streaming should be continuous rather than one-shot at end

### ISSUE THREAD

**Issue by chenel** [DUNE/larnd-sim#57]
The current design of `cli/simulate_pixels.py` saves all output at the end of its run.  For larger inputs, this tends to result in out-of-memory issues since everything doesn't fit in memory at once.  Since h5 datasets support extending in-place, we should be writing to the file continuously (store after every event?), which would eliminate this problem.

**Comment by soleti** [comment]
Fixed by PR #58.
