### ISSUE TITLE
Document output file format

### ISSUE THREAD

**Issue by peter-madigan** [DUNE/larnd-sim#82]
While the primary `packets` dataset is documented within `larpix-control`, there isn't any specific documentation for the mc truth information or the light simulation. This is important for allowing downstream code to interface with larnd-sim.

**Comment by soleti** [comment]
I restructured the documentation after PR #92. A stub is now present at https://github.com/DUNE/larnd-sim/blob/master/docs/source/output.rst.

**Comment by peter-madigan** [comment]
Addressed by #100
